image: ruby:2

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8
  BUNDLE_PATH: ./vendor/bundle

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

before_script:
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  environment:
    name: gitlab-pages
    url: http://status.bitnp.net
  only:
  - master
