url: https://status.narro.co
author: NarroApp
email: josh@narro.co
title: Narro Status
description: The status page for the Narro API and services

permalink: pretty

# TODO: Build pagination into archive
gems: [jekyll-paginate]
paginate: 2
paginate_path: '/archive/page:num/'
