url: https://status.bitnp.net
author: BITNP
email: webmaster@bitnp.net
title: BITNP 服务状态
description: BITNP 网站服务状态信息
homepage: https://www.bitnp.net

permalink: pretty
uptime_days: 14

timezone:	Asia/Shanghai

# TODO: Build pagination into archive
plugins: [jekyll-paginate]
paginate: 2
paginate_path: '/archive/page:num/'

include: [".well-known", "_kqkBDtb0XV0ep4Ihuii4h5yDWEyZ1IZQgNQ8DDv5_I"]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      author: "BITNP"