url: https://status.bitnp.net
author: BITNP
email: webmaster@bitnp.net
title: BITNP 服务状态
description: BITNP 网站服务状态信息
homepage: https://www.bitnp.net

permalink: pretty
uptime_days: 14

# TODO: Build pagination into archive
gems: [jekyll-paginate]
paginate: 2
paginate_path: '/archive/page:num/'
